apiVersion: apps/v1
kind: Deployment
metadata:
  name: coord-deploy
spec:
  replicas: 4
  selector:
    matchLabels:
      app: utsav-coord
  template:
    metadata:
      labels:
        app: utsav-coord
    spec:
      containers:
      - name: coord-utsav
        image: registry.digitalocean.com/utsav-rot-24/coordinators:1.0.6
        ports:
        - containerPort: 4173