apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing-deploy
spec:
  replicas: 4
  selector:
    matchLabels:
      app: utsav-landing
  template:
    metadata:
      labels:
        app: utsav-landing
    spec:
      containers:
      - name: landing-utsav
        image: registry.digitalocean.com/utsav-rot-24/landing_page:1.1.1
        ports:
        - containerPort: 4173