apiVersion: apps/v1
kind: Deployment
metadata:
  name: camp-deploy
spec:
  replicas: 4
  selector:
    matchLabels:
      app: utsav-camp
  template:
    metadata:
      labels:
        app: utsav-camp
    spec:
      containers:
      - name: camp-utsav
        image: registry.digitalocean.com/utsav-rot-24/campaining:1.0.6
        ports:
        - containerPort: 4173