apiVersion: apps/v1
kind: Deployment
metadata:
  name: authportal-deploy
spec:
  replicas: 4
  selector:
    matchLabels:
      app: utsav-authportal
  template:
    metadata:
      labels:
        app: utsav-authportal
    spec:
      containers:
      - name: authportal-utsav
        image: registry.digitalocean.com/utsav-rot-24/auth-portal:1.0.8
        ports:
        - containerPort: 4173