apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: myapp
  name: myapp-config-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage